# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '~> 5.2.2'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'database_cleaner'
  gem 'factory_bot_rails', '~> 4.8.2'
  gem 'faker', '~> 1.9.1'
  gem 'rspec-rails', '~> 3.8'
  gem 'simplecov', '~> 0.15'
end

group :development do
  gem 'rubocop', '~> 0.64.0'
  gem 'spring'
  gem 'web-console', '~> 3.5.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
